### ISSUE TITLE
Implement Landing Page 

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#1]
Please ensure that the design of the landing page matches the exact design provided in the Figma file. This includes accurately replicating the layout, styles, and assets. Attention to detail is crucial— the final implementation must be pixel-perfect, responsive, and fully aligned with the provided design specifications.

**Please ensure to provide an ETA.**

https://www.figma.com/design/dwXPww5jcUl55azC9EQ8H0/SCANGUARD?node-id=14-12&t=CY2laF37qFH954NR-1

**Looking forward to seeing your great work!**

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a frontend developer with experience in JS, react and typescript. 

### How I plan on tackling this issue
I have gone throught the figma design provided. ETA <= 78hr

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello I am a front-end and a blockchain developer. I will love to work on this issue please

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will follow the UI to ensure that the final implementation will be pixel-perfect, responsive, and fully aligned with the provided design specifications.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
hello @zintarh i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
Task Summary:

- Implement the landing page design to match the provided Figma file precisely.
- Replicate layout, styles, and assets with pixel-perfect accuracy.
- Ensure the page is responsive and fully aligned with the design specifications.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will design the Landing Page according to the specifications outlined in the provided Figma file. My focus will be on accurately replicating the layout, styles, and assets to ensure that the final design is pixel-perfect and fully responsive across different devices.

Attention to detail will be my top priority. I will carefully match every aspect of the design, including typography, color schemes, spacing, and image placement, to ensure that the final implementation aligns perfectly with the design specifications. This will not only enhance the visual appeal but also create a cohesive user experience.

Also, I will ensure that the landing page is optimized for performance and usability, making it easy for users to navigate and interact with the content. I will also incorporate responsive design principles, so the page looks great on both desktop and mobile devices.
My ETA is 3days.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue
I will be sure to implement the details of the figma to exact requirements.

will be done with this in 2 days.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/

### How I plan on tackling this issue
To ensure the design of the landing page matches the specifications provided in the Figma file, I will follow these steps:

Thoroughly Review the Figma File: I will carefully examine the Figma design to understand the layout, styles, and assets required for the landing page. This review will help me identify all elements that need to be accurately replicated.

Replicate Layout and Styles: I will implement the layout as per the Figma design, ensuring that all sections are arranged correctly. This includes using the specified grid system, spacing, and alignment to maintain the intended visual hierarchy.

Utilize Provided Assets: I will extract and use all necessary assets (images, icons, etc.) directly from the Figma file, ensuring that they are of the highest quality and accurately positioned on the landing page.

Ensure Pixel-Perfect Implementation: I will focus on achieving a pixel-perfect implementation by comparing the developed landing page against the Figma design. This involves meticulous attention to detail, ensuring that fonts, colors, margins, and paddings are aligned exactly as specified.

Implement Responsiveness: I will ensure that the landing page is fully responsive by using media queries and flexible layouts, allowing the design to adapt seamlessly to different screen sizes and devices.

Testing and Quality Assurance: After implementation, I will conduct thorough testing to verify that the landing page matches the Figma design across various devices and browsers, ensuring functionality and visual fidelity.

ETA: I estimate that this task will take approximately [insert your estimated time, e.g., 5-6days] to complete. This includes the design implementation, testing, and any necessary adjustments based on feedback.

**Comment by melnikga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hi, my name is Georgiy, I'm a frontend developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

### How I plan on tackling this issue
I would create a pixel-perfect implementation of the landing page using Tailwind CSS. I'd ensure exact replication of design elements by using shadcn components for consistent styling. For layout and spacing, I'd implement the precise measurements from the Figma specifications, focusing on accurate typography, colors, and spacing. To maintain design fidelity, I'd set up proper responsive breakpoints to ensure the layout adapts perfectly across all screen sizes while preserving the intended visual hierarchy and component relationships.

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I Have a strong background as UI designer

### How I plan on tackling this issue
Design the landing page according to project vision and brand guidelines.
ETA 24hrs

**Comment by DanielEmmanuel1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello, my name is Deon, I’m a Full stack web3 developer with a strong passion for creating intuitive and user-friendly interfaces. I have experience in modern JavaScript frameworks as well as ample expereience in CSS and frameworks like tailwind, bootstrap, scss amongst others, which allows me to effectively translate design concepts into functional web applications.

### How I plan on tackling this issue
- First, I’ll carefully review the Figma design to fully understand the layout, styles, and assets that need to be replicated. I’ll make sure to take note of every detail.

- After that, I’ll start building the page, ensuring that everything down to the pixel, making a perfect match to the design. I’ll focus on making sure the layout, typography, colors, and assets are all spot-on.

- Responsiveness is key, so I’ll ensure that the landing page looks great and functions smoothly across all devices, from desktops to mobile.

- Once the page is implemented, I’ll conduct thorough testing to ensure everything is aligned properly, both visually and functionally.

- Based on the testing, I’ll make any necessary adjustments to guarantee a pixel-perfect final version.

After that, I’ll share the completed page with the for feedback, and I’ll make any additional tweaks if needed.

I can start the design today complete the project within the next 48 hours tops.

**Comment by Abeeujah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm a Frontend Web Developer skilled in replicating designs to be Pixel Perfect and ensuring every web component is usable and functional.

### How I plan on tackling this issue
- Implement the Layout and ensure the use of Semantic MarkUp Elements
- Ensure the styling and branding matches the design spec
- Pay attention to details and micro interactions, animations and ensure they're functional.

ETA 36HRs

**Comment by wheval** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hey there,  I'm Wheval, a frontend developer with several experience building pixel-perfect, responsive and great user experiences with React, typescript and tailwindcss. I can replicate the landing page perfectly, even with some interactions.  I would really love to contribute. I would ensure to replicate the design perfectly.

### How I plan on tackling this issue
First, I would inspect the Figma file to get the brand guidelines like colors, fonts sizes and assets.
Next, I would create components that would be used across multiple pages to ensure reusable code. 
I know how much attention to details matter on the landing page, so I would ensure I replicate every single part of the design to be according to design.
I would also make sure the page is responsive using different media queries depending on screen sizes and also ensure fluid width of the layout element and font sizes according to the existing UI design of the page.
Also, i built https://declanwork.xyz/.

ETA 2days

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a python dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by Dev-AndresGR** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I have experience designing in figma and flutterflow. Html and others
I have created apps on my own, both in frontend and backend, and I am very good at it.
I currently have a couple of repositories of one pages that I am creating, you can check them out.
And as a member of the Dojo Coding , I am aware of related news.
I think this could be my first good issue
Me considero capaz de lograr este issue, pues he diseñado apps para empresas, siguiendo reglas de diseño, cómo colores, logos, medidas, que sea responsive.

### How I plan on tackling this issue
The first thing would be to request the figma file, study each page well, learn color patterns, designs, sizes and logos.
Then I create a new tab on one monitor and on the other the figma pages already created so that I can always have them as a reference and that they are completely the same and following the same patterns.
I am quite creative, so you will like it

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

### How I plan on tackling this issue
My Approach includes:
- Reviewing, studying and Analyzing the Figma design.
- Implement the design layout by layout, component by component.
- Create a Pull Request (PR).
- Request for a Review.
- Make changes based on the Review of the PR.

**Comment by EjembiEmmanuel** [comment]
@Abeeujah assigned you. Good luck!

**Comment by zintarh** [comment]
Hi @Abeeujah, just checking in on the progress. Could we get a PR soon? Issue #12 is pending this completion to move forward

**Comment by Abeeujah** [comment]
Hi @zintarh yeah, sure you would, tomorrow!

**Comment by zintarh** [comment]
Completed via #27
