### ISSUE TITLE
feat: migrate product submission logic from `expressjs` to `nestjs`

### ISSUE THREAD

**Issue by EjembiEmmanuel** [nexlabsweb3/scanguard#24]
### This issues is part of ODHACK 9.0, apply via the platform

**Description:** Currently, our `product.ts` file in the Express API contains the logic for submitting a product and uploading its data to IPFS using Pinata.  We want to implement the same feature in the Nestjs API to improve code structure, scalability, and maintainability.

**Task Objectives:**
1. Create a DTO (Data Transfer Object) for validating incoming product data.
2. Implement a Product Service to handle:
    - Product ID generation.
    - Communication with the IPFS (Pinata) API to pin product data.
    - Error handling in case of failed IPFS uploads.
3. Set up a Product Controller that:
    - Receives product data as a POST request.
    - Validates product data using the DTO.
    - Interacts with the Product Service to upload the product data to IPFS.
    - Returns the IPFS hash or an appropriate error message.
4. Organize with a Product Module to encapsulate service and controller for modularity.
5. Integrate the Product Module into the main application.

**Resources:**
- Existing `product.ts` and `utils.ts` files in `express_backend` for reference.

**Comment by ikemHood** [comment]
Can I get on this?

**Comment by vitaliypopel** [comment]
I will do my best for replacing expressjs to nestjs, i have a great background with backend and nodejs

**Comment by Cyberking99** [comment]
Hello, with my experience on uploading files to Pinata using their API and skills on Nestjs, I can migrate the product form submission login from Expressjs to Nestjs.
