### ISSUE TITLE
Upgrade Contracts to Cairo 2.8.4 

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#3]
This issues is part of ODHACK 9.0, apply via the platform

Upgrade Contracts to Cairo 2.8.4 

**Please ensure to provide an ETA.**

Looking forward to seeing your great work!

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello I am a front-end and a blockchain developer. I will love to work on this issue please

**Comment by nickgore** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hi, I'm data analyst / SC dev. For last half a year i ve been participating in development of  DeFi products on Starknet, thus i have quite extensive hands on experience with Cairo. I would love to contribute to this issue or tackle something more challenging.

### How I plan on tackling this issue
Update Scarb.toml
Make sure dependencies are compatible with new version
Tackle depricated features. 
ETA - saturday morning CET

**Comment by ptisserand** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm a senior cairo developer with strong experience in Starknet ecosystem (since cairo 0). I have contributed to several projects on Only Dust writing smart contract code or rust backend.

### How I plan on tackling this issue
After updating contract to 2.8.4 (at least LegacyMap -> Map), I will also update dependencies versions (OZ and starknet-foundry).
ETA: 2 days

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
I'll upgrade the contracts to cairo v2.8.4 and adjust necessary dependencies without breaking the already existing functionality and tests.

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I’m a software developer experienced in smart contract development particularly with Cairo. I prioritize contract security during upgrades and have a solid background in testing and contracts.

### How I plan on tackling this issue
I will analyze the current contracts for breaking changes in version 2.8.4, update the syntax and dependencies, and ensure all tests pass and functionality remains intact.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past.

### How I plan on tackling this issue
I will study the Cairo codebase and will carefully upgrade to the latest Cairo version with the latest additions to the language and best practice.
I will also update the dependencies and Starknet Foundry to the latest versions.

ETA 1 day.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I have a strong background in smart contract development, particularly with Cairo, which equips me with the skills necessary to upgrade existing contracts to the latest version, Cairo 2.8.4. My experience with code refactoring and understanding of the latest features and improvements in Cairo will ensure a smooth transition and optimization of the contracts.


### How I plan on tackling this issue
To upgrade the contracts to Cairo 2.8.4, I will begin by reviewing the existing contract codebase to identify all dependencies and functionalities that may be affected by the upgrade. I will then consult the Cairo 2.8.4 release notes and migration guides to understand the changes and new features. Following this, I will methodically refactor the code, ensuring compatibility with the new version and testing each component to validate its functionality. I will also run comprehensive tests to ensure all functionalities perform as expected post-upgrade. Finally, I will provide an estimated timeline for the completion of the upgrade, which is 3 to 5 working days. factoring in the testing and potential debugging phases.

**Comment by EjembiEmmanuel** [comment]
@ptisserand I've assigned you. Goodluck!
