### ISSUE TITLE
Implement product verification

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#32]
This issues is part of ODHACK 10.0, apply via the platform

This issues depends on #35 

**Description:**  

**Task** 

- Retrieve the product-generated hash from the backend and use it to call the smart contract for verification.

- Since retrieving the hash is handled by the issues above, simply call the integrated function to obtain the hash and pass it to the contract's verify function.

- Ensure that the existing code in `/scan/product` is updated to work seamlessly with the latest backend and includes 
  functionality to call the contract for product verification.

**Looking forward to seeing your great work!**

**Comment by myspace20** [comment]
@zintarh I would like to work on this issue

**Comment by 0xdevcollins** [comment]
Can I be assigned to this?

**Comment by jaykayudo** [comment]
Can I be assigned to this?

I am a highly skiled typescript and Blockchain developer with a passion for building innovative, scalable solutions.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
Would love to tackle this! I can comfortably handle this issues

**Comment by Benjtalkshow** [comment]
I'd love to give this a go.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by CollinsC1O** [comment]
I'd love to work on this!

**Comment by myspace20** [comment]
Can I take this issue?

**Comment by caxtonacollins** [comment]
Would love to tackle this! applying from onlydust

**Comment by Unickhub** [comment]
Can I contribute to this one?

**Comment by ShantelPeters** [comment]
Can I tackle this one?

**Comment by Michaelkingsdev** [comment]
I'd like to handle this task.

**Comment by zintarh** [comment]
Hello @Joewizy , I'll have to unassign you if I don't see a PR today.

**Comment by myspace20** [comment]
@zintarh I will be on standby to take up this issue.

**Comment by Joewizy** [comment]
@zintarh working on it would update the PR today.
