### ISSUE TITLE
Display Product Details on Overview Screen

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#33]
This issues is part of ODHACK 10.0, apply via the platform

Description:

Fetch and display product details on the product overview screen by integrating with the backend API. Ensure the data is presented clearly and aligns with the design specifications.

Looking forward to seeing your great work!

**Comment by KevinLatino** [comment]
Hello @zintarh! My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I know how to fetch and display product details accurately on the product overview screen, ensuring alignment with Figma designs and functionality. My experience integrating backend APIs and attention to detail make me confident in delivering high-quality results.

I think I will finish this issue in 10 hours

**Comment by qgatssdev** [comment]
I can get this done in less than two days if assigned. I'm a fullstack engineer with over 4 years of experience.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
Would love to tackle this! I can comfortably handle this issues

**Comment by estherbreath** [comment]
I am a Smart contract and a full stack developer and would like to handle this issue.

To approach this issue, I will take the following appoaches.

implement a RESTful API endpoint in the backend to fetch product details based on a unique identifier.

On the frontend, I will create a React component to display the fetched data, ensuring alignment with the provided design specifications. 

I'll utilize Redux for state management to optimize performance and reusability. 

Additionally, l will  implement error handling and loading states to enhance user experience.

Finally, I'll conduct thorough testing, including unit tests and integration tests, to ensure robustness and reliability

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by josephchimebuka** [comment]
Would love to tackle this!

**Comment by Ayoazeez26** [comment]
Is it okay if I tackle this?
I would get the data from the backend API and render on the product overview screen. I would make sure this works as expected and test before submitting a PR
ETA - 2 days

**Comment by Villarley** [comment]
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would follow all the guidelines and instructions to get exactly what you want.
Pls feel free to reach out!

**Comment by Unickhub** [comment]
Can I handle this task?

**Comment by wheval** [comment]
Hello @zintarh, 

My name is Wheval. I'm a front-end developer and onlydust open-source contributor. I have experience with React, Next.js, and TypeScript. I also have experience working with apis.

I would ensure the product details are correctly displayed from the backend endpoint. I would also handle errors properly while following the current design specifications.

ETA is 2 days.

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by MullerTheScientist** [comment]
hello please can i address this issue

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by Oshioke-Salaki** [comment]
I'd be happy to do this. I am a well seasoned frontend developer experienced in Next, Typescript and Tailwind. I have worked on various projects on the onlydust platform and would love to work on this issue.
