### ISSUE TITLE
Create Manufacturer Account Form/Route

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#34]
This issues is part of ODHACK 10.0, apply via the platform

Description:
 The registration form should capture details such as:
- Company Name
- Manufacturer Name
- Means of Company Identification

**Comment by KevinLatino** [comment]
Hello @zintarh! My name is Kevin Latino, and I'm a front-end developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I will design and implement registration forms to capture essential details such as company name, manufacturer name, and means of company identification. I will apply robust validation techniques to ensure data integrity and securely transmit the registration data to the backend.

I think I will finish this issue in 9 hours

**Comment by 0xdevcollins** [comment]
I'd like to handle this task.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by ShantelPeters** [comment]
Can I take this issue?

**Comment by MullerTheScientist** [comment]
Would love to  address this issue

**Comment by MrRoudyk** [comment]
Can I tackle this one?

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by Ekene001** [comment]
Hello, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I'd like to handle this issue

**Comment by DanielEmmanuel1** [comment]
Mind if I try this one?

How I Plan To Solve This Issue

I’ll start by creating a rough paper sketch of how the overall UI of the form should be, creating input fields to collect data like company name, manufacturer name & means of company identification (e.g., an upload option or dropdown for document type).

After creating a rough sketch, my next step will be to start the coding process, upon going through your repo’s frontend i am aware that it is built using Next.js framework which am well conversant with, I will create a ManufacturerForm.tsx and build up the form structure and ensure all inputs are properly validated, checking for things like empty fields, correct formats, and file types.

Finally, once the form is ready and validated on the frontend, I’ll set up a POST request to send the data to an API endpoint, (I’m guessing that has been created prior to this task) where it will be processed and saved to the backend. I’ll ensure the data is sent securely and handle any responses or errors appropriately.

ETA: 48 hours.

**Comment by codebestia** [comment]
I’d like to work on this.

Step I'll take to solve this

- Finalize the form with frontend validation in place.
- Set up a POST request to send the data to the API endpoint.
- Ensure the API endpoint processes and saves the data to the backend.
- Implement secure data transmission during the request.
- Handle API responses and errors appropriately.

ETA: 48 hours.

**Comment by Amarjeet325** [comment]
I’d like to help with this.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)
