### ISSUE TITLE
 Product Submission and Hash Generation

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#35]
This issues is part of ODHACK 10.0, apply via the platform

Description:
The form should collect the following details:

- Product Name
- Product Image
- Manufacturing Date
- Expiry Date

Once the data is submitted, send it to the backend to generate a unique hash for the product, and then record the hash on the contract.

Looking forward to seeing your great work!

**Comment by qgatssdev** [comment]
Hello, I believe this should be easy to handle. I can get this done in good time so I can continue contributing. I'm a fullstack engineer with over 4 years of experience.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
Is this issue still available?

**Comment by Michaelkingsdev** [comment]
Can I work on this, please?

**Comment by zintarh** [comment]
Hello @qgatssdev , I'll have to unassign you if I don't see a PR today.
