### ISSUE TITLE
Create alert system components

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#36]
This issues is part of ODHACK 10.0, apply via the platform

Description:

Create components to display alert messages for both success and error scenarios. Ensure the components are customizable, user-friendly, and able to handle different types of messages effectively.

Looking forward to seeing your great work!

**Comment by NueloSE** [comment]
@zintarh kindly assign. ETA <= 2days

**Comment by KevinLatino** [comment]
Hello @zintarh! My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I will create components to display alert messages for both success and error scenarios, ensuring they are customizable, user-friendly, and capable of handling different types of messages effectively. I will focus on making these components intuitive and responsive to improve the overall user experience.

I think I will finish this issue in 6 hours

**Comment by CollinsC1O** [comment]
Hi @zintarh I would love to tackle this!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Joewizy** [comment]
Would love to tackle this!

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by josephchimebuka** [comment]
Could I grab this task?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by jsandinoDev** [comment]
Hi  I'm a full-stack developer from Costa Rica and member of Dojo coding. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

Steps to fix it:
1. Design the Alert Component

You will create a generic Alert component that can be customized based on the type of message (success, error, or other types).

2. Steps to Implement:

	•	Step 1: Define Alert Types
	•	The alert should support multiple types, like success, error, info, and warning, each with different visual styles.
	•	Step 2: Customize Styles
	•	Use CSS-in-JS (like styled-components or TailwindCSS) to style each alert differently based on the type.
	•	Step 3: Allow Custom Messages
	•	The component should accept message as a prop, which will be the dynamic content to display.
	•	Step 4: Auto-dismissal (Optional)
	•	For user convenience, consider adding a timer to automatically dismiss the alert after a few seconds.
	•	Step 5: Accessibility
	•	Ensure that the component is accessible (e.g., screen reader-friendly).

**Comment by caxtonacollins** [comment]
I'd love to give this a go.

**Comment by Villarley** [comment]
I'd like to take this isI’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I would follow all the guidelines and instructions to get exactly what you want.
Pls feel free to reach out!sue.

**Comment by ShantelPeters** [comment]
May I try my hand at this?

**Comment by austineblaise** [comment]
This is my first time contributing to an OnlyDust project ... I can create customizable alert components for success and error messages. These will be user-friendly, flexible, and handle different message types effectively.

Looking forward to contributing!

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.
