### ISSUE TITLE
Display Registered Products from Manufacturers

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#37]
This issues is part of ODHACK 10.0, apply via the platform

This issue depends #39 

Description:

Display products uploaded by manufacturers on their dashboard, showing key details like name, image, and unique identifier. Allow easy management of registered products with options to edit or remove them

Looking forward to seeing your great work!

**Comment by KevinLatino** [comment]
Hello @zintarh! My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I will display products uploaded by manufacturers on their dashboard, ensuring key details like name, image, and unique identifier are presented clearly. I will also implement easy management options, allowing manufacturers to edit or remove their registered products efficiently.
I think I will finish this issue in 8 hours

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by josephchimebuka** [comment]
Could I be assigned to this?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by Ayoazeez26** [comment]
I’m interested in this one.
I would implement this by showing the key details mentioned above, and also allow management of registered products with options to edit or remove the products

ETA - 3 days

**Comment by caxtonacollins** [comment]
i am applying this issue throught onlydust
I’d like to work on this.

**Comment by Unickhub** [comment]
May I take care of this?

**Comment by ShantelPeters** [comment]
I’m interested in this one.

**Comment by Oshioke-Salaki** [comment]
I'd be happy to do this. I am a well seasoned frontend developer experienced in Next, Typescript and Tailwind. I have worked on various projects on the onlydust platform and would love to work on this issue.

**Comment by Kaminar-i** [comment]
May I take this issue on?

**Comment by Kaminar-i** [comment]
Please, can I take on this task
