### ISSUE TITLE
Implement manufacturer registration logic

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#38]
Implement the business logic for manufacturer registration in the existing module. Integrate Prisma ORM, handle validation, and ensure proper error handling.

**Tasks:**
1. Service implementation:
    - Save manufacturers using Prisma.
    - Handle errors.
 
2. Controller implementation:
    - Implement POST `/manufacturer/register`.
    - Validate input using `CreateManufacturerDto`.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Benjtalkshow** [comment]
Mind if I try this one?

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by ncoquelet** [comment]
I’d like to work on this.

# Presentation

Hello, I'm senior developer, comfortable with Typescript, React/Vite/Next, testing, CI/CD, docs and I'm a beginner on Cairo (starklings 100% and NodeGuardians “Entering Cairo”, “Thinking in Cairo”, “Vanity Address”, and I continue).
I'm rigorous and diligent, I'm used to contributing my skills to projects and can move really quickly.

# How do I resolve this issue?

Understand the real need and propose the simple way to implement it.

**Comment by ShantelPeters** [comment]
Can I attempt this issue?

**Comment by MullerTheScientist** [comment]
would love to address this issue

**Comment by Michaelkingsdev** [comment]
I’d love to work on this task.

**Comment by Amarjeet325** [comment]
Can I try solving this issue?
