### ISSUE TITLE
Generate Product Hash

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#39]

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
Would love to tackle this! I can comfortably handle this issues

**Comment by Benjtalkshow** [comment]
May I pick this up?

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contribution to similar tasks(https://app.onlydust.com/u/Josh-121) looking to make first contribution on this project

How I plan on tackling this issue
would use product unique attributes to generate hash
work on feedback & recommendation ensuring contact. Can deliver within a day upon assignment

**Comment by caxtonacollins** [comment]
Could I take on this issue? ETA 24 hours

**Comment by ShantelPeters** [comment]
Can I be assigned to this?

**Comment by MullerTheScientist** [comment]
Mind if I try this one?

**Comment by akintewe** [comment]
Mind if I try this one?

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by Kaminar-i** [comment]
Please, can I be assigned this task
