### ISSUE TITLE
Implement dark and light mode options for enhanced user experience

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#42]
This issues is part of ODHACK 10.0, apply via the platform

Description:

Add dark and light mode options to enhance user comfort and accessibility by allowing a customizable interface based on user preferences.

Looking forward to seeing your great work!

**Comment by imoleayomi19** [comment]
May I handle this issue?Yes 
I am a Front-end developer. I am proficient in CSS, Typescript, JavaScript.
I would love to work on this project.

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

will glaldy like to tackle this issue by adding if statement but making light the default and dark an option when clicked 

thanks

**Comment by Kaminar-i** [comment]
Can i be assigned this?

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario and typescript,  would love to work on this , my ETA is >12 Hours and ill create a draft PR in 10 hours time. Thank you for this opportunity. :)

**Comment by Kingsuite** [comment]
Can I handle this task?

**Comment by martinvibes** [comment]
I'd love to work on this!
hey @zintarh kindly assign

**Comment by NueloSE** [comment]
I’m interested in this one.

ETA <= 3hrs

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by CollinsC1O** [comment]
I'd love to work on this!

**Comment by Ekene001** [comment]
Hello, I'm a frontend and blockchain developer with expertise in Rust, Cairo, Next.js, TypeScript, React, and Node.js. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. 

Please can I assist with this task?
