### ISSUE TITLE
Set background image from the design on the landing page.

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#43]
This issues is part of ODHACK 10.0, apply via the platform

Description:

Incorporate the background image from the design into the landing page to enhance its visual appeal and align with the overall aesthetic.

Looking forward to seeing your great work!

**Comment by dahtee** [comment]
Hi @zintarh can I work on this?
I'm a full stack developer and I'm new to onlydust. I'll love to contribute to this project.

**Comment by Kingsuite** [comment]
I'd love to work on this!

It's my first time working on this project

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario and typescript, would love to work on this , my ETA is >6 Hours and ill create a draft PR in 2 hours time. Thank you for this opportunity. :)

**Comment by zintarh** [comment]
Hello @Kingsuite Can I get a PR today

**Comment by Kingsuite** [comment]
Hi @zintarh I am rounding up today. I'll do so in a good time

**Comment by Kingsuite** [comment]
@zintarh I've created a PR
