### ISSUE TITLE
Fix video playback issue on the landing page.

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#44]
This issues is part of ODHACK 10.0, apply via the platform

Description:
Fix video playback issue on the landing page.

Looking forward to seeing your great work!

**Comment by SYLVIANNORUKA** [comment]
Hello. I'm a Front-end developer and i'm new to onlydust. I am good with Tailwind css,react and nextjs.

**Comment by starknetbrother** [comment]
I'm a new contributor and would love to work on this

1. **Inspect Issues**:  
   - Use browser dev tools to check for console errors or failed network requests for the video file.  

2. **Verify Source**:  
   - Ensure the video URL is correct, accessible, and in a compatible format (e.g., MP4).  

3. **Review Code**:  
   - Confirm `<video>` attributes like `src`, `controls`, and `autoplay` are correctly set.  

4. **Check Hosting**:  
   - Ensure the server supports video delivery and CORS if hosted externally.  

5. **Test & Deploy**:  
   - Test fixes locally and in staging before deploying to production.
