### ISSUE TITLE
Implement manufacturer dashboard

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#47]
This issues is part of ODHACK 10.0, apply via the platform

Thank you for showing interest!

**Task**

Please implement the manufacturer dashboard, ensuring it matches the provided design. This is a conversion task, so the screen must be replicated exactly with attention to detail. It should be responsive and fully aligned with the design. 

Follow the design style presented in the Figma link, using the theme's colors for consistency.  

https://www.figma.com/design/FwfYO5bDcWPLHkfrw4s9C9/Dashboard?node-id=26-50&node-type=frame&t=xUV0dKbWSlITYw6w-0

- **Button Text:** *Add Product*  
- **Table Columns:**  
  - **Product Name**  
  - **Created Date**  
  - **Expiry Date**"
 
Please ensure to provide an ETA.

Looking forward to seeing your great work!

**Comment by NueloSE** [comment]
I’d like to resolve this.

**Comment by Jethrolopwus** [comment]
Hi my name is Jethro Lopwus, I am a frontend developer with skills and expertise in react.js and next.js.

With my frontend knowledge, I will like to work on this issue by implementing the manufacturer's dashboard design.

With the provided design, I will ensure I implement the design as it is, while paying attention to detail and making the design responsive on all screen sizes to align with the design.

The ETA for this is 2 days.

**Comment by viktrified** [comment]
Is it okay if I take this? I'm a frontend developer.
I'll work on responsive design for various screen sizes, ensuring it looks and functions well on desktops, tablets, and mobile devices. 
Please share the design files (figma) so I can evaluate the complexity and provide an accurate ETA. If the dashboard is straightforward, I estimate 2–3 days, assuming no major dependencies or additional functionalities.

**Comment by martinvibes** [comment]
Hey @zintarh can I work on this issue 
I'm a frontend and blockchain dev 
ETA: 48hrs
