### ISSUE TITLE
Implement logic to retrieve all manufacturers

### ISSUE THREAD

**Issue by EjembiEmmanuel** [nexlabsweb3/scanguard#49]
Implement logic to retrieve all manufacturers from the database with pagination support.

**Tasks:**
1. Service:
    - Implement logic to retrieve all manufacturers using Prisma.
    - Return a list of manufacturers.

2. Controller:
    - Add GET /manufacturer endpoint.

**Comment by Benjtalkshow** [comment]
Hello @EjembiEmmanuel 
Can i work on this issue? 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by Michaelkingsdev** [comment]
I would love to work on this issue. i have extensive experience working with backend technologies using express and node. My ETA is 48hrs.

**Comment by OJDIT** [comment]
I'd love to give this a go.
