### ISSUE TITLE
Implement logic to retrieve manufacturer by ID

### ISSUE THREAD

**Issue by EjembiEmmanuel** [nexlabsweb3/scanguard#50]
Implement logic to retrieve all manufacturers from the database with pagination support.

**Tasks:**
1. Service:
    - Implement logic to retrieve manufacturer by ID using Prisma.
    - Return a manufacturer.

2. Controller:
    - Add GET /manufacturer/:id endpoint.

**Comment by 0xdevcollins** [comment]
Can I tackle this one?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by akintewe** [comment]
Hi my name is akintewe, I am a frontend developer with skills and expertise in typescript and next.js.

I would like to work on this issue by implementing the logic to retrieve manufacturers data 



The ETA for this is 1 day.

**Comment by Kaminar-i** [comment]
Let me handle this issue!
i will like to work on this issue

**Comment by Jagadeeshftw** [comment]
I'd love to work on this!

**Comment by saimeunt** [comment]
Hey I have experience working with Prisma: https://github.com/walnuthq/op-scan/blob/main/prisma/schema.prisma
I'd like to work on this one.

**Comment by Aditya-040** [comment]
I'd love to work on this!

**Comment by Joewizy** [comment]
I'd like to handle this task.

**Comment by No-bodyq** [comment]
Can I take care of this issue?

**Comment by Rayguti** [comment]
Why I’m Interested: This task offers a great opportunity to work with Prisma ORM and deepen my understanding of backend development, particularly in handling database queries efficiently. I'm excited to contribute by building an API endpoint that will provide manufacturers' data in a clean and secure manner.

Proposed Approach:

    Service:
        Logic Implementation: Implement logic within the service to interact with Prisma and retrieve all manufacturers from the database.
        Data Return: Ensure the list of manufacturers is returned as an array of objects with all necessary manufacturer details.
        Pagination Consideration (Optional): If the manufacturer data set is large, consider implementing pagination or limit/offset parameters to avoid overloading the response.

    Controller:
        Create Endpoint: Add a new GET /manufacturer endpoint in the controller to handle the request.
        Service Integration: Ensure the endpoint correctly calls the service logic to retrieve the manufacturer data.
        Error Handling: Implement proper error handling for any potential issues, such as no manufacturers being found or server/database errors.
        Response Format: Ensure the response is formatted consistently, ideally returning a JSON array of manufacturers.

Testing:

    Test the new GET /manufacturer endpoint to ensure it returns the correct data.
    Verify that the logic handles edge cases like an empty manufacturer database.
    Ensure that error handling works properly, providing useful error messages if issues arise.

**Comment by abdegenius** [comment]
Is it okay if I tackle this?

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.


I estimate this will take 12-24 hours to complete.

This is how I would tackle this issue:

Implement a service function using Prisma to fetch all manufacturers with pagination logic.
Create a GET /manufacturer controller endpoint to handle the request and return the paginated results.
Test the endpoint to ensure it retrieves data correctly and handles edge cases like empty pages or invalid inputs.
This would be my first contribution, and with my strong TypeScript background, I’m confident I'd be able to deliver a really nice solution.
Pls feel free to reach out!!!

**Comment by Abishake01** [comment]
I'm Willing to contribute . Hi I'm Abishake , I am a web developer, Actually its my first #ODHack if you give an opportunity for me to contribute I explore my skill .
To implement pagination for retrieving manufacturers, use a backend language like Node.js with Prisma for database interaction.

**Comment by Xaxxoo** [comment]
Could I take over this issue?

**Comment by Supa-mega** [comment]
I'd be happy to do this.

**Comment by chigozzdevv** [comment]
Hello, can I take this from here? I'm a full stack app and web developer. 

I have worked with Prisma, Mongodb, and Typescript do demonstrate hexagonal architecture implementation.

**Comment by emarc99** [comment]
I’d like to help with this. I have backend experience. And test endpoints as well.

**Comment by nora360** [comment]
May I take this issue on?

**Comment by olisaagbafor** [comment]
I’d like to help with this.

**Comment by DotworldX** [comment]
I’d like to help with this.

**Comment by Birdmannn** [comment]
Could I be assigned to this?

**Comment by CEOliam** [comment]
May I take this issue on?

**Comment by vestor-dev** [comment]
Is it okay if I tackle this
@zintarh kindly assign

**Comment by mimisavage** [comment]
Can I attempt this issue?

**Comment by aniruddhaaps** [comment]
To address this issue I would:
1.  use Prisma's findMany method with skip and take parameters for pagination.

const getManufacturers = async (page: number, limit: number) => {
    return await prisma.manufacturer.findMany({
        skip: (page - 1) * limit,
        take: limit,
    });
};

2. Then I would add a GET /manufacturer endpoint to call the service, extracting page and limit from query parameters. Return the paginated results to the client.
