### ISSUE TITLE
Backend Integration for Manufacturer Account Creation  

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#53]
This issues is part of ODHACK 10.0, apply via the platform

Description:
### Task: 
Integrate the backend with the existing manufacturer account creation design. Consume the API, implement robust validation, and securely transmit the registration data to the backend.

**Comment by System625** [comment]
Hello
I've check the onlydust app when the ODHack10 is taking place but the issue has not appeared there.

**Comment by 0xdevcollins** [comment]
Can I start working on this?

**Comment by Jagadeeshftw** [comment]
I’d like to work on this.

**Comment by System625** [comment]
Hello! I'd love to take on this manufacturer account integration task. 
I have experience working with backend API integrations, user authentication and account management flows too. I've previously built registration systems with strong validation logic and secure data handling ensuring smooth backend integration.
I am able to complete this task if given the chance

**Comment by akintewe** [comment]
Hello good day i am happy to work on this project as a new contributor

i have experience in Cairo and javascript.

i also have good logic skills from backend integration to backend data fetch REST APIs etc.

would love to work on this issue, my ETA is >24 hours

**Comment by System625** [comment]
Hello! I'd love to take on this manufacturer account integration task. 
I have experience working with backend API integrations, user authentication and account management flows too. I've previously built registration systems with strong validation logic and secure data handling ensuring smooth backend integration.
I am able to complete this task if given the chance

**Comment by Joy-Adah** [comment]
Hello. I am a web3 developer, technical writer and contributor and I have experience integrating backends with existing designs. I'll ensure that the API is consumed and that the registration data is securely transmitted to the backend. I plan to have a draft PR ready as soon as possible.

**Comment by Birdmannn** [comment]
Could I grab this task?

**Comment by OWK50GA** [comment]
Hey, @zintarh
Let me work on this

**Comment by emarc99** [comment]
Can I take this?

Will be my first contribution.

**Comment by Supa-mega** [comment]
I’d like to help with this.

**Comment by Aditya-040** [comment]
Can I take this issue?

**Comment by Villarley** [comment]
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on projects built on StarkNet and Stellar, creating scalable and efficient solutions. I’m also a Web3 hackathon Buildathon winner for my work on BuildMyEvent, an open-source blockchain project solving real-world challenges.

I estimate this task will take 2–3 days to complete.

To resolve this, I’ll integrate the backend with the manufacturer account creation design by consuming the API, implementing robust validation, and securely transmitting registration data to the backend. I’ll ensure all work aligns with the project’s requirements and guidelines.

Pls feel free to reach out

**Comment by No-bodyq** [comment]
I'd be happy to do this.

**Comment by Joy-Adah** [comment]
Hello. I am a web3 developer, technical writer and contributor and I have experience integrating backends with existing designs. I'll ensure that the API is consumed and that the registration data is securely transmitted to the backend. I plan to have a draft PR ready as soon as possible.

**Comment by olisaagbafor** [comment]
I’d like to help with this.
