### ISSUE TITLE
Create and emit events for register_product() 

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#6]
This issues is part of ODHACK 9.0, apply via the platform

Thank you for showing interest!

Ensure that relevant data is captured in the events

Depends on #3

**Please ensure to provide an ETA.**

Looking forward to seeing your great work!

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a full-stack and web3 dev with experience in writing smart contracts in Cairo

### How I plan on tackling this issue
I will create a struct that derives from the starknet event trait and add the data fields to be be emitted with the event, add the event to an event enum then ensure it is properly emitted when the function is called
ETA is 2 days

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer. I will love to solve this issue. please assign

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
i will Add event emission to the register_product() function.
Create a new ProductRegistered event instance with the relevant data.

**Comment by Oshioke-Salaki** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hello i am a frontend developer and cairo developer and i believe i would be able to tackle this issue effectively.

### How I plan on tackling this issue
I would create the function and also write tests for the function to make usre that it works as expected. While creating the function i would make sure that it emits the appropiate event. i would also test that the event was fired off.

**Comment by ptisserand** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm a senior cairo developer with strong experience in Starknet ecosystem (since cairo 0).
I have contributed to several projects on Only Dust writing smart contract code or rust backend.

### How I plan on tackling this issue
After added event struct definition in smart contract, I will ensure that events are emitted through starknet foundry tests
ETA: 0.5 day

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I'm a nestjs backend Engineer who transitioned into web3, smart contract development

### How I plan on tackling this issue
Create properties to store product id and ifps hash from the register product function to the storage variables and create an event which will emit the parameterized inputs.
ETA: 3 hours

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
I'll create the function with the expected functionality and full test coverage.
ETA- 2days

**Comment by jimenezz22** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I am Luis Jiménez, an active member of the Dojo Coding community in Costa Rica, with experience in Cairo, having built onchain games like ByteBeasts and contributed to open-source projects such as CairoLint, where I implemented tests for Cairo lints. Additionally, I taught Cairo during the Starknet Bootcamp for Dojo Coding. I also have experience with TypeScript, contributing to Starknet Quest and Go Stark Me by developing components like ComboBoxes, among others

### How I plan on tackling this issue
Here’s my approach for tackling the issue:

1. **Understanding Event Requirements:**
    - I’ll review the current implementation of the `register_product()` function to understand the data it handles. Based on this, I’ll identify the critical fields (e.g., product ID, owner address, registration timestamp) that need to be included in the event.
2. **Creating the Event:**
    - I’ll define a Cairo event structure that captures the relevant data, ensuring it follows the best practices for event design and is efficiently emit during product registration.
3. **Emitting the Event:**
    - I’ll update the `register_product()` function to emit the event with the necessary data points at the correct stage of the registration process.
4. **Testing:**
    - I’ll write unit tests to verify that the event is emitted correctly and that it contains the expected data when the `register_product()` function is called.
5. **ETA:**
    - I estimate this task will take approximately is 3-5 days, which includes time for development, testing, and any necessary revisions.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past such as https://github.com/ArkProjectNFTs/bridge/pull/236

### How I plan on tackling this issue
I will carefully add the necessary Starknet event and will make sure to emit it correctly where it is required.

ETA 1 day.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/scanguard).

### My background and how it can be leveraged
 I have a strong foundation in developing decentralized applications and smart contracts, which allows me to understand and implement the requirements effectively. My experience with event-driven programming and blockchain technology positions me well to ensure that the relevant data captured in the events meets both technical and user requirements.


### How I plan on tackling this issue
To address the issue of ensuring that relevant data is captured in the events, I will first review the existing event definitions and identify any missing attributes necessary for comprehensive tracking. Then, I will modify the event emitters to include the required data points. After updating the code, I will conduct thorough testing to ensure that all events are emitted correctly and contain the expected data. Additionally, I will provide documentation to outline the changes made and their implications. I estimate that the implementation will take approximately [3 to 5 working days ] to complete.

**Comment by EjembiEmmanuel** [comment]
@Oshioke-Salaki I've assigned you. This issue depends on #3, so you can begin work as soon as it is completed.

**Comment by EjembiEmmanuel** [comment]
@Oshioke-Salaki this issue is now open as #3has been completed.
