### ISSUE TITLE
Fix dependencies conflict 

### ISSUE THREAD

**Issue by zintarh** [nexlabsweb3/scanguard#63]
Resolve the dependency conflict between @starknet-react/core and starknet packages in the project. 

<img width="737" alt="Screenshot 2024-11-26 at 6 50 37 AM" src="https://github.com/user-attachments/assets/0151d53e-435e-4f5e-a4c1-0b9cfac839df">

**Acceptance Criteria:**  
The `npm install` command should execute successfully without any peer dependency conflicts.

**Comment by sajalbnl** [comment]
I’d like to resolve this.

**Comment by Kaminar-i** [comment]
Gm can i do this? I am a web3 frontend developer with experience in building dapps.
