### ISSUE TITLE
Implement flag product endpoint

### ISSUE THREAD

**Issue by EjembiEmmanuel** [nexlabsweb3/scanguard#72]
Develop functionality to enable users submit flagged products

**Tasks:**
**1.  Controller Implementation:**
- Add a `flagProduct` function in the `backend/src/product/product.controller.ts` file.
- Define a POST endpoint `flag` to handle product flagging requests.
- Use the `FlagProductDto` in `backend/src/product/dto/flag-product.dto.ts` file  to validate the request payload

**2.  Service Implementation:**
- Implement the `flagProduct` function in the `backend/src/product/product.service.ts` file to handle the business logic for flagging products.
- This function should store the flagged product in the database.

**Comment by baitcode** [comment]
Hey, Hey!
Background: https://app.onlydust.com/u/baitcode
Can I take care of this issue?
