### ISSUE TITLE
Implement get flagged products endpoint

### ISSUE THREAD

**Issue by EjembiEmmanuel** [nexlabsweb3/scanguard#74]
Develop functionality to get flagged products

**Tasks:**
**1.  Controller Implementation:**
- Add a `getFlaggedProduct` function in the `backend/src/product/product.controller.ts` file.
- Define a GET endpoint `flag` to handle get flagged products requests.

**2.  Service Implementation:**
- Implement the `getFlaggedProduct` function in the `backend/src/product/product.service.ts` file to handle the business logic for getting flagging products.
- This function should retrieve flagged products from the database.

**Comment by baitcode** [comment]
Hey, Hey!
Background: https://app.onlydust.com/u/baitcode
Can I take care of this issue?

**Comment by ikemHood** [comment]
Can I take this issue?

**Comment by babsKambai** [comment]
I'd like to handle this task.
